{{- if and (not .Values.redis.existingSecret) .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ai.fullname" . }}-redis
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.password }}
  password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ai.fullname" . }}-ai
  labels:
    {{- include "paperless-ai.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.llm.apiKey }}
  llm-api-key: {{ .Values.config.llm.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.huggingface.apiKey }}
  huggingface-api-key: {{ .Values.config.huggingface.apiKey | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.config.vectorDb.provider "pinecone" }}
  {{- if .Values.config.vectorDb.pineconeApiKey }}
  pinecone-api-key: {{ .Values.config.vectorDb.pineconeApiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.config.vectorDb.provider "weaviate" }}
  {{- if .Values.config.vectorDb.weaviateApiKey }}
  weaviate-api-key: {{ .Values.config.vectorDb.weaviateApiKey | b64enc | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}
