{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-database
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.password }}
  password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-app
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if .Values.config.secretKey }}
  secret-key: {{ .Values.config.secretKey | b64enc | quote }}
  {{- else }}
  secret-key: {{ randAlphaNum 50 | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.adminPassword }}
  admin-password: {{ .Values.config.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.emailHostPassword }}
  email-password: {{ .Values.config.emailHostPassword | b64enc | quote }}
  {{- end }}
---
{{- end }}
