name: Publish Helm chart

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Update chart dependencies
        run: helm dependency update .

      - name: Lint chart
        run: helm lint .

      - name: Package chart
        run: helm package . --destination docs

      - name: Create Helm repo index
        run: helm repo index docs --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages