name: Publish Helm chart

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow pushing code (charts & index)
  pages: write      # allow updating Pages artifacts

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true  # ensure ${GITHUB_TOKEN} is in .git/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update chart dependencies
        run: helm dependency update .

      - name: Lint chart
        run: helm lint .

      - name: Package chart
        run: helm package . --destination docs

      - name: Create Helm repo index
        run: |
          helm repo index docs \
            --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/docs

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages